services:
  server:
    build:
      context: .
    restart: always
    image: port-of-mars/server:dev
    secrets:
      - pom_db_password
      - mail_api_key
      - secret_key
      - google_client_secret
      - facebook_client_secret
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - ./docker/dump:/dump
      - ./docker/logs:/var/log/port-of-mars
      - ./keys/.pgpass:/root/.pgpass
      - ./keys/settings.json:/run/secrets/settings.json
      - ./scripts:/scripts
      - ./.prettierrc:/code/.prettierrc
  redis:
    image: redis:7
    restart: always
  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marsmadness -d port_of_mars"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:15-bookworm
    secrets:
      - pom_db_password
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/pom_db_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/data:/var/lib/postgresql/data/pgdata

secrets:
  pom_db_password:
    file: ./keys/pom_db_password
  mail_api_key:
    file: ./keys/mail_api_key
  secret_key:
    file: ./keys/secret_key
  google_client_secret:
    file: ./keys/google_client_secret
  facebook_client_secret:
    file: ./keys/facebook_client_secret
