services:
  server:
    build:
      context: .
    restart: always
    image: port-of-mars/server/dev:latest
    depends_on:
      - redis
      - db
    volumes:
      - ./docker/dump:/dump
      - ./docker/logs:/var/log/port-of-mars
      - ./keys/ormconfig.json:/code/server/ormconfig.json
      - ./keys/.pgpass:/root/.pgpass
      - ./keys:/run/secrets
      - ./scripts:/scripts
      - ./server/.env:/code/server/.env
        #  XXX: nuxt disabled until typeorm + auth support is properly added
        #  https://github.com/virtualcommons/port-of-mars/issues/795
        #  https://github.com/virtualcommons/port-of-mars/issues/809
        #  nuxt:
        #    build:
        #      context: pom-nuxt
        #    image: port-of-mars/web
        #    ports:
        #      - '127.0.0.1:3000:3000'
        #    volumes:
        #      - ./pom-nuxt:/code/web
        #      - ./server:/code/server
        #      - ./shared:/code/shared
        #      - ./keys/ormconfig.ts:/code/web/ormconfig.ts:ro
        #      - /code/web/node_modules
  redis:
    image: redis:7
    restart: always
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: marsmadness
      POSTGRES_PASSWORD_FILE: /run/secrets/pom_db_password
      POSTGRES_DB: port_of_mars
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./keys/pom_db_password:/run/secrets/pom_db_password:ro
      - ./docker/data:/var/lib/postgresql/data/pgdata
