services:
  client:
    build:
      dockerfile: client/Dockerfile
      context: .
    restart: always
    image: port-of-mars/client:dev
    env_file:
      - .env
    volumes:
      - ./client:/code/client
      - ./shared/src:/code/shared/src
      - /code/client/node_modules
      - ./.prettierrc:/code/.prettierrc
    ports:
      - "127.0.0.1:8081:8080"
  server:
    build:
      dockerfile: server/Dockerfile.dev
    ports:
      - "127.0.0.1:2567:2567"
    volumes:
      - ./server:/code/server
      - ./shared:/code/shared
      - /code/server/node_modules
