services:
  redis:
    volumes:
      - ./docker/redis:/data
  server:
    build:
      dockerfile: server/deploy/Dockerfile.prod
      args:
        NODE_ARG: production
    image: port-of-mars/server:prod
    ports:
      - '2567:2567'
