name: Build/Test Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure for dev environment to run tests
      run: ./configure dev
    - name: Compile TS code for production
      run: make buildprod
    - name: Run tests
      run: make test
    
